### PR TITLE
make babylon plugins configurable

### PR DESCRIPTION
**Pull request by mziwisky**
i need me some `dynamicImport`!

### CODE REVIEW

**Comment by mziwisky** [comment]
hey @jenseng, hows it going? :)

hoping to get this published by early next week.  you planning on maintaining this still, or should I just fork it for my needs?

**Comment by jenseng** [comment]
Aw yiss, thx z!

I'm not actively using i18nliner atm, but I'm happy to merge pull requests that come along. But if I'm ever not responsive enough and you want to run with it, just lemme know and I can give you github and npm privs.

**Comment by jenseng** [comment]
ok 0.2.5 has been pushed to npm 🎉

**Comment by mziwisky** [comment]
Thanks Jon!  If I find myself getting too needy, I'll take you up on the privs offer.  For now, my needs are met, and I'm happy to hold as little responsibility as possible ;)

**Pull request merged**
